version: '3'
services:
  loca-backend:
    build: .
    restart: always
    command:
      - yarn
      - debug
    environment:
      JWT_SECRET: foobar
      JWT_ISSUER: loca-backend-dev
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: postgres
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: ""
      TYPEORM_PORT: "5432"
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "true"
      TYPEORM_ENTITIES: "src/entities/**/*.ts"
      TYPEORM_MIGRATIONS: "src/migrations/**/*.ts"
      TYPEORM_SUBSCRIBERS: "src/subscribers/**/*.ts"
      TYPEORM_ENTITIES_DIR: "src/entities"
      TYPEORM_MIGRATIONS_DIR: "src/migrations"
      TYPEORM_SUBSCRIBERS_DIR: "src/subscribers"
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src:consistent
      - ./views:/usr/src/app/views:consistent
    depends_on:
      - postgres
    stdin_open: true
    tty: true
  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ""
    ports:
      - 5432:5432
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
